# Generated by Django 3.2.22 on 2023-12-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
